/**
 * snap-cricut.js — Cricut Print-then-Cut export for Snap Station
 * Generates a ZIP with a print PNG (+ registration marks) and a cut SVG.
 * Requires JSZip (loaded via CDN in snap-station.html).
 */

class CricutExporter {
  /**
   * Generate a Cricut-ready export package (ZIP with PNG + SVG).
   * @param {HTMLCanvasElement} stickerCanvas
   * @param {object} options
   * @returns {Promise<Blob>}
   */
  static async generateKissCutPackage(stickerCanvas, options = {}) {
    const {
      cutOffset = 2,
      stickerRows = 4,
      stickerCols = 4,
      sheetWidthMm = 120,
      sheetHeightMm = 180,
    } = options;

    const printCanvas = this.addRegistrationMarks(stickerCanvas);
    const printPng = printCanvas.toDataURL('image/png', 1.0);
    const svgContent = this.generateCutSVG({ sheetWidthMm, sheetHeightMm, stickerRows, stickerCols, cutOffset });

    if (typeof JSZip === 'undefined') {
      throw new Error('JSZip is required for Cricut export. Please check your internet connection.');
    }

    const zip = new JSZip();
    zip.file('snap_station_PRINT.png', printPng.split(',')[1], { base64: true });
    zip.file('snap_station_CUT.svg', svgContent);
    zip.file('README.txt', this.instructions);

    return zip.generateAsync({ type: 'blob' });
  }

  /**
   * Draw registration marks on a copy of the canvas.
   * @param {HTMLCanvasElement} source
   * @returns {HTMLCanvasElement}
   */
  static addRegistrationMarks(source) {
    const canvas = document.createElement('canvas');
    canvas.width = source.width;
    canvas.height = source.height;
    const ctx = canvas.getContext('2d');
    ctx.drawImage(source, 0, 0);

    // Registration marks: 3 corners, black 15x15px squares
    const markSize = Math.round(source.width * 0.02);
    const margin = Math.round(source.width * 0.01);
    const corners = [
      [margin, margin],
      [source.width - margin - markSize, margin],
      [margin, source.height - margin - markSize],
    ];
    ctx.fillStyle = '#000000';
    corners.forEach(([x, y]) => ctx.fillRect(x, y, markSize, markSize));
    return canvas;
  }

  static generateCutSVG({ sheetWidthMm, sheetHeightMm, stickerRows, stickerCols, cutOffset }) {
    const cellW = sheetWidthMm / stickerCols;
    const cellH = sheetHeightMm / stickerRows;
    const off = cutOffset;

    let paths = '';
    for (let r = 0; r < stickerRows; r++) {
      for (let c = 0; c < stickerCols; c++) {
        const x = (c * cellW + off).toFixed(2);
        const y = (r * cellH + off).toFixed(2);
        const w = (cellW - 2 * off).toFixed(2);
        const h = (cellH - 2 * off).toFixed(2);
        paths += `    <rect x="${x}" y="${y}" width="${w}" height="${h}" rx="2" ry="2" />\n`;
      }
    }

    const marks = [
      { x: 5, y: 5 },
      { x: sheetWidthMm - 10, y: 5 },
      { x: 5, y: sheetHeightMm - 10 },
    ].map(({ x, y }) => `  <rect x="${x}" y="${y}" width="5" height="5" fill="black" />`).join('\n');

    return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg"
     width="${sheetWidthMm}mm" height="${sheetHeightMm}mm"
     viewBox="0 0 ${sheetWidthMm} ${sheetHeightMm}">
  <!-- Registration marks for Cricut Print-then-Cut -->
${marks}
  <!-- Kiss-cut paths (sticker outlines) -->
  <g fill="none" stroke="black" stroke-width="0.1">
${paths}  </g>
</svg>`;
  }

  static get instructions() {
    return `CRICUT PRINT-THEN-CUT INSTRUCTIONS
=====================================
1. Print snap_station_PRINT.png on your sticker paper
   - Use highest quality setting
   - Select actual size (no scaling)

2. Load the printed sheet into your Cricut machine

3. Open Cricut Design Space
   - Create a new project
   - Click "Upload" > upload snap_station_CUT.svg
   - Set the layer type to "Cut"

4. Enable Print-then-Cut mode
   - The registration marks will be detected automatically

5. Set cut pressure for your sticker paper (kiss cut)
   - Kiss cut goes through vinyl/sticker layer only, not backing

6. Cut and peel your stickers!

Generated by Pokemon Snap Station
`;
  }
}

// ─── Cricut Export Button Handler ─────────────────────────────────────────────

function initCricutExport() {
  const btn = document.getElementById('cricutExportBtn');
  if (!btn) return;

  btn.addEventListener('click', async () => {
    const canvas = document.getElementById('stickerSheetCanvas') || document.getElementById('captureCanvas');
    if (!canvas || canvas.width === 0) {
      alert('No sticker sheet to export. Take some photos first!');
      return;
    }

    btn.textContent = 'Generating...';
    btn.disabled = true;

    try {
      const blob = await CricutExporter.generateKissCutPackage(canvas);
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = 'snap_station_cricut.zip';
      a.click();
      URL.revokeObjectURL(url);
    } catch (err) {
      alert(`Export failed: ${err.message}`);
    } finally {
      btn.textContent = 'Download for Cricut';
      btn.disabled = false;
    }
  });
}

window.CricutExporter = CricutExporter;
document.addEventListener('DOMContentLoaded', initCricutExport);
